function inertiaMatrix = inertiaMatrix(in1)
%inertiaMatrix
%    inertiaMatrix = inertiaMatrix(IN1)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    13-Feb-2023 11:09:47

q1 = in1(1,:);
q2 = in1(2,:);
t2 = cos(q1);
t3 = cos(q2);
t4 = sin(q1);
t5 = sin(q2);
t6 = t2.*5.0e+1;
t7 = t4.*5.0e+1;
t8 = t2.*t3.*2.5e+1;
t9 = t2.*t5.*2.5e+1;
t10 = t3.*t4.*2.5e+1;
t11 = t4.*t5.*2.5e+1;
t12 = (t2.*t3)./2.0;
t13 = (t2.*t5)./2.0;
t14 = (t3.*t4)./2.0;
t15 = (t4.*t5)./2.0;
t16 = -t11;
t17 = -t15;
t18 = t9+t10;
t20 = t13+t14;
t19 = t8+t16;
t21 = t12+t17;
t22 = t4+t20;
t24 = t7+t18;
t23 = t2+t21;
t25 = t6+t19;
t26 = (t18.*t22)./2.0;
t28 = (t20.*t24)./2.0;
t27 = (t19.*t23)./2.0;
t29 = (t21.*t25)./2.0;
t30 = t26+t27+t28+t29+1.0e+1;
inertiaMatrix = reshape([t22.*t24+t23.*t25+t2.^2.*(2.5e+1./2.0)+t4.^2.*(2.5e+1./2.0)+2.0e+1,t30,t30,t18.*t20+t19.*t21+1.0e+1],[2,2]);
