function modifiedInertiaMatrix = modifiedInertiaMatrix(in1)
%modifiedInertiaMatrix
%    modifiedInertiaMatrix = modifiedInertiaMatrix(IN1)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    13-Feb-2023 11:09:46

q1 = in1(1,:);
q2 = in1(2,:);
t2 = cos(q1);
t3 = cos(q2);
t4 = sin(q1);
t5 = sin(q2);
t6 = q1+q2;
t7 = cos(t6);
t8 = sin(t6);
t9 = t2.*5.0e+1;
t10 = -t4;
t11 = t4.*5.0e+1;
t12 = t2.*t3.*2.5e+1;
t14 = t2.*t5.*2.5e+1;
t15 = t3.*t4.*2.5e+1;
t16 = t4.*t5.*2.5e+1;
t17 = (t2.*t3)./2.0;
t18 = (t2.*t5)./2.0;
t19 = (t3.*t4)./2.0;
t20 = (t4.*t5)./2.0;
t13 = -t8;
t21 = -t16;
t22 = -t20;
t24 = t14+t15;
t26 = t18+t19;
t23 = t7+t13;
t25 = t12+t21;
t27 = t17+t22;
t29 = t4+t26;
t31 = t11+t24;
t28 = t2+t10+t23;
t30 = t2+t27;
t32 = t9+t25;
t33 = (t24.*t29)./2.0;
t35 = (t26.*t31)./2.0;
t34 = (t25.*t30)./2.0;
t36 = (t27.*t32)./2.0;
t37 = t33+t34+t35+t36+1.0e+1;
modifiedInertiaMatrix = reshape([t29.*t31+t30.*t32+t2.^2.*(2.5e+1./2.0)+t4.^2.*(2.5e+1./2.0)+2.0e+1,t37,t28,t37,t24.*t26+t25.*t27+1.0e+1,t23,t28,t23,0.0],[3,3]);
