function [tau,Y_new] = fungen_TAU_Y(q1,q2,dq1,dq2,ddq1,ddq2,tau1,tau2)
%fungen_TAU_Y
%    [TAU,Y_new] = fungen_TAU_Y(Q1,Q2,DQ1,DQ2,DDQ1,DDQ2,TAU1,TAU2)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    23-Feb-2024 11:20:03

tau = [tau1;tau2];
if nargout > 1
    t2 = cos(q2);
    t3 = sin(q2);
    t4 = ddq1+ddq2;
    Y_new = reshape([ddq1,0.0,t4,t4,ddq1.*t2.*2.0+ddq2.*t2-dq2.*t3.*(dq1+dq2)-dq1.*dq2.*t3,ddq1.*t2+dq1.^2.*t3,dq1,dq2],[2,4]);
end
