function KineticEnergy = KineticEnergy(in1,in2)
%KINETICENERGY
%    KINETICENERGY = KINETICENERGY(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    17-Feb-2021 11:43:34

dq1 = in2(1,:);
dq2 = in2(2,:);
q1 = in1(1,:);
q2 = in1(2,:);
t2 = cos(q1);
t3 = cos(q2);
t4 = sin(q1);
t5 = sin(q2);
t6 = dq2.*5.0;
t7 = t2.*5.0e+1;
t8 = t4.*5.0e+1;
t9 = t2.*t3.*2.5e+1;
t10 = t2.*t5.*2.5e+1;
t11 = t3.*t4.*2.5e+1;
t12 = t4.*t5.*2.5e+1;
t13 = (t2.*t3)./2.0;
t14 = (t2.*t5)./2.0;
t15 = (t3.*t4)./2.0;
t16 = (t4.*t5)./2.0;
t17 = -t12;
t18 = -t16;
t19 = t10+t11;
t21 = t14+t15;
t20 = t9+t17;
t22 = t13+t18;
t23 = t4+t21;
t25 = t8+t19;
t24 = t2+t22;
t26 = t7+t20;
KineticEnergy = dq2.*(dq1.*5.0+t6)+dq1.*(dq1.*1.0e+1+t6)+dq2.*((dq2.*(t19.*t21+t20.*t22))./2.0+(dq1.*(t21.*t25+t22.*t26))./2.0)+dq1.*((dq1.*(t23.*t25+t24.*t26+t2.^2.*(2.5e+1./2.0)+t4.^2.*(2.5e+1./2.0)))./2.0+(dq2.*(t19.*t23+t20.*t24))./2.0);
