function P2 = Pend(in1)
%PEND
%    P2 = PEND(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    17-Feb-2021 11:43:34

q1 = in1(1,:);
q2 = in1(2,:);
t2 = cos(q1);
t3 = cos(q2);
t4 = sin(q1);
t5 = sin(q2);
P2 = [t2+t2.*t3-t4.*t5;t4+t2.*t5+t3.*t4;0.0];
