function potentialEnergy = potentialEnergy(in1)
%POTENTIALENERGY
%    POTENTIALENERGY = POTENTIALENERGY(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    17-Feb-2021 11:43:35

q1 = in1(1,:);
q2 = in1(2,:);
t2 = sin(q1);
potentialEnergy = t2.*7.35e+2+cos(q1).*sin(q2).*2.45e+2+t2.*cos(q2).*2.45e+2;
